---
- name: Create Active Directory users from CSV using PowerShell
  hosts: windows
  gather_facts: no
  tasks:

    - name: Execute PowerShell script to create AD users
      ansible.windows.win_shell: |
        powershell.exe -ExecutionPolicy Bypass -File C:\path\to\create_ad_users.ps1
      register: output

    - name: Display output
      ansible.builtin.debug:
        var: output.stdout_lines
