---
- name: Create Active Directory users 
  hosts: Domain_controller
  gather_facts: no
  tasks:
    - name: Create AD users
      microsoft.ad.user:
        name: "{{ username }}"
        given_name: "{{ firstname }}"
        surname: "{{ lastname }}"
        password: "{{ password }}"
        user_principal_name: "{{ username }}.{{ lastname }}"
        email: "{{ email }}"
        state: present
        enabled: yes
        password_never_expires: yes
        require_password_change: no
      delegate_to: remote_windows_host
