---
- name: Create Active Directory users from CSV
  hosts: localhost
  gather_facts: no
  tasks:
#    - name: Read CSV file
#      ansible.builtin.csvfile:
#        path: https://github.com/Felipe-Henriquez-Gonzalez/lighspeed-demo/blob/main/users.csv
#      register: user_list

    - name: Create AD users
      community.windows.win_domain_user:
        name: "{{ item.username }}"
        given_name: "{{ item.firstname }}"
        surname: "{{ item.lastname }}"
        password: "{{ item.password }}"
        user_principal_name: "{{ item.username }}@yourdomain.com"
        email: "{{ item.email }}"
        state: present
        enabled: yes
        password_never_expires: yes
        require_password_change: no
      loop: "{{ user_list.list }}"
      delegate_to: remote_windows_host
