---
- name: Launch EC2 instance
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Create a security group
      amazon.aws.ec2_group:
        name: ansible-security-group
        description: Security group for Ansible EC2 instance
        region: us-east-1
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: security_group

    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        key_name: your_key_pair_name
        instance_type: t2.micro
        image_id: ami-0c55b159cbfafe1f0  # Amazon Linux 2 AMI
        wait: yes
        region: us-east-1
        group: "{{ security_group.group_id }}"
        count: 1
        instance_tags:
          Name: AnsibleEC2Instance
      register: ec2

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ ec2.instances[0].public_ip }}"
        port: 22
        delay: 60
        timeout: 320
        state: started

    - name: Add new instance to host group
      add_host:
        hostname: "{{ ec2.instances[0].public_ip }}"
        groupname: launched

    - name: Wait for SSH to be available
      wait_for_connection:
        delay: 10
        timeout: 320
        state: started
