---
- name: validar version de sistema operativo y actualizar 
  hosts: all
  become: yes

  tasks:
  #chequear que la version del sistema operativo sea rhel 9 & actualizar kernel en vivo & actualizar parches de seguridad
  # Content suggestion provided by Ansible Lightspeed
  - name: Chequear que la version del sistema operativo sea rhel 9
    ansible.builtin.fail:
      msg: Sistema operativo no soportado
    when: ansible_distribution_major_version != "9"

  - name: Actualizar kernel en vivo
    ansible.builtin.package:
      name: kernel
      state: latest

