---
- name: Crear usuarios 
  hosts: Domain_controller
  gather_facts: no

  tasks:
    - name: Leer el archivo CSV
      community.general.read_csv:
        path: c:\\csv\users.csv
      register: csv_content

    - name: Creando usuario
      debug:
        msg: "{{ item }}"
      loop: "{{ csv_content.list }}"
