---
- name: Crear usuarios 
  hosts: demo.local
  gather_facts: no

  tasks:
    - name: Generar Listado de usuarios
      community.general.read_csv:
        path: /root/users.csv
      register: csv_content

    - name: Creando usuario
      debug:
        msg: "{{ item }}"
      loop: "{{ csv_content.list }}"
